import { Material } from '../shared/material.model';

export class ListaTkaninService {

  private listaTkanin: Material[] = [
    { nazwa: 'Amy', imgPath: 'tkan (1).jpg' },
    { nazwa: 'azteckie zwierzątka', imgPath: 'tkan (2).jpg' },
    { nazwa: 'baletnice', imgPath: 'tkan (3).jpg' },
    { nazwa: 'balony i proporczyki na błękicie', imgPath: 'tkan (4).jpg' },
    { nazwa: 'balony proporczyki na jasnym', imgPath: 'tkan (5).jpg' },
    { nazwa: 'chevron mięta pomarańcz', imgPath: 'tkan (6).jpg' },
    { nazwa: 'chevron mięta szary', imgPath: 'tkan (7).jpg' },
    { nazwa: 'czarne pieski', imgPath: 'tkan (8).jpg' },
    { nazwa: 'domki', imgPath: 'tkan (9).jpg' },
    { nazwa: 'dream team', imgPath: 'tkan (10).jpg' },
    { nazwa: 'dziki zachód', imgPath: 'tkan (11).jpg' },
    { nazwa: 'dziobaki', imgPath: 'tkan (12).jpg' },
    { nazwa: 'etniczna 02', imgPath: 'tkan (13).jpg' },
    { nazwa: 'flamingi pastelowe', imgPath: 'tkan (14).jpg' },
    { nazwa: 'folkowe koniki', imgPath: 'tkan (15).jpg' },
    { nazwa: 'forest', imgPath: 'tkan (16).jpg' },
    { nazwa: 'gadające ptaszki', imgPath: 'tkan (17).jpg' },
    { nazwa: 'geometric 04', imgPath: 'tkan (18).jpg' },
    { nazwa: 'geometric 07 trójkąty róz czarny', imgPath: 'tkan (19).jpg' },
    { nazwa: 'geometric 09 piramidki zóty czarny', imgPath: 'tkan (20).jpg' },
    { nazwa: 'geometric 10 etniczna', imgPath: 'tkan (21).jpg' },
    { nazwa: 'geometric cube', imgPath: 'tkan (22).jpg' },
    { nazwa: 'geometric kolorowe trójkąty', imgPath: 'tkan (23).jpg' },
    { nazwa: 'gwiazdki na szarym', imgPath: 'tkan (24).jpg' },
    { nazwa: 'gwiazdki szare na białym', imgPath: 'tkan (25).jpg' },
    { nazwa: 'hiszpańska rozeta', imgPath: 'tkan (26).jpg' },
    { nazwa: 'jabłka', imgPath: 'tkan (27).jpg' },
    { nazwa: 'jaskółki', imgPath: 'tkan (28).jpg' },
    { nazwa: 'jednorożce na różu', imgPath: 'tkan (29).jpg' },
    { nazwa: 'jednorożce tęcza baloniki', imgPath: 'tkan (30).jpg' },
    { nazwa: 'jelenie', imgPath: 'tkan (31).jpg' },
    { nazwa: 'jednorożce na szarym', imgPath: 'tkan (32).jpg' },
    { nazwa: 'kocie łapki', imgPath: 'tkan (33).jpg' },
    { nazwa: 'kocurki', imgPath: 'tkan (34).jpg' },
    { nazwa: 'kolorowe autka', imgPath: 'tkan (35).jpg' },
    { nazwa: 'kolorowe kropelki', imgPath: 'tkan (36).jpg' },
    { nazwa: 'kolorowe sówki', imgPath: 'tkan (37).jpg' },
    { nazwa: 'kosmos', imgPath: 'tkan (38).jpg' },
    { nazwa: 'kotki i motylki', imgPath: 'tkan (39).jpg' },
    { nazwa: 'kotki w kołach', imgPath: 'tkan (40).jpg' },
    { nazwa: 'koty na niebieskim', imgPath: 'tkan (41).jpg' },
    { nazwa: 'kozioki', imgPath: 'tkan (42).jpg' },
    { nazwa: 'koła i kotwice', imgPath: 'tkan (43).jpg' },
    { nazwa: 'księżniczki na różu', imgPath: 'tkan (44).jpg' },
    { nazwa: 'księżniczki na fiolecie', imgPath: 'tkan (45).jpg' },
    { nazwa: 'laleczki', imgPath: 'tkan (46).jpg' },
    { nazwa: 'las muchomory', imgPath: 'tkan (47).jpg' },
    { nazwa: 'latające piórka', imgPath: 'tkan (48).jpg' },
    { nazwa: 'leśne zwierzaki na jasnym', imgPath: 'tkan (49).jpg' },
    { nazwa: 'liski geometryczne', imgPath: 'tkan (50).jpg' },
    { nazwa: 'liski miętowo-pomarańczowe', imgPath: 'tkan (51).jpg' },
    { nazwa: 'lisy na niebieskim', imgPath: 'tkan (52).jpg' },
    { nazwa: 'lisy w lesie na szarym', imgPath: 'tkan (53).jpg' },
    { nazwa: 'maszyny budowlane', imgPath: 'tkan (54).jpg' },
    { nazwa: 'misie i tipi na brązie', imgPath: 'tkan (55).jpg' },
    { nazwa: 'misie z zabawką', imgPath: 'tkan (56).jpg' },
    { nazwa: 'miś polarny na granacie', imgPath: 'tkan (57).jpg' },
    { nazwa: 'miś polarny na mięcie', imgPath: 'tkan (58).jpg' },
    { nazwa: 'morze', imgPath: 'tkan (59).jpg' },
    { nazwa: 'muffinki', imgPath: 'tkan (60).jpg' },
    { nazwa: 'niedźwiedzie geometryczne', imgPath: 'tkan (61).jpg' },
    { nazwa: 'owocowy miodek', imgPath: 'tkan (62).jpg' },
    { nazwa: 'pieski na brązie', imgPath: 'tkan (63).jpg' },
    { nazwa: 'pieski różowo - brązowe', imgPath: 'tkan (64).jpg' },
    { nazwa: 'pieski', imgPath: 'tkan (65).jpg' },
    { nazwa: 'piraci', imgPath: 'tkan (66).jpg' },
    { nazwa: 'pióra i koraliki', imgPath: 'tkan (67).jpg' },
    { nazwa: 'pojazdy i samoloty', imgPath: 'tkan (68).jpg' },
    { nazwa: 'polana', imgPath: 'tkan (69).jpg' },
    { nazwa: 'powiew wiosny', imgPath: 'tkan (70).jpg' },
    { nazwa: 'ptaki na gałązkach', imgPath: 'tkan (71).jpg' },
    { nazwa: 'ptasia tęcza', imgPath: 'tkan (72).jpg' },
    { nazwa: 'ptasie budki', imgPath: 'tkan (73).jpg' },
    { nazwa: 'ptasie chmurki', imgPath: 'tkan (74).jpg' },
    { nazwa: 'ptaszki i króliczki na mięcie', imgPath: 'tkan (75).jpg' },
    { nazwa: 'pączki', imgPath: 'tkan (76).jpg' },
    { nazwa: 'roboty', imgPath: 'tkan (77).jpg' },
    { nazwa: 'romby miętowe', imgPath: 'tkan (78).jpg' },
    { nazwa: 'romby', imgPath: 'tkan (79).jpg' },
    { nazwa: 'rozeta', imgPath: 'tkan (80).jpg' },
    { nazwa: 'safari', imgPath: 'tkan (81).jpg' },
    { nazwa: 'szopy', imgPath: 'tkan (82).jpg' },
    { nazwa: 'sówki zielone', imgPath: 'tkan (83).jpg' },
    { nazwa: 'słowiki', imgPath: 'tkan (84).jpg' },
    { nazwa: 'Teddy na białym', imgPath: 'tkan (85).jpg' },
    { nazwa: 'Teddy nocą', imgPath: 'tkan (86).jpg' },
    { nazwa: 'trójkąciki na białym', imgPath: 'tkan (87).jpg' },
    { nazwa: 'trójkąty różowo niebieskie', imgPath: 'tkan (88).jpg' },
    { nazwa: 'trójkąty turkus', imgPath: 'tkan (89).jpg' },
    { nazwa: 'wzór etniczny', imgPath: 'tkan (90).jpg' },
    { nazwa: 'wzór kaszubski', imgPath: 'tkan (91).jpg' },
    { nazwa: 'wzór łowicki na czarnym', imgPath: 'tkan (92).jpg' },
    { nazwa: 'wzór łowicki', imgPath: 'tkan (93).jpg' },
    { nazwa: 'zakochane myszki', imgPath: 'tkan (94).jpg' },
    { nazwa: 'zwierzaki w kółkach na białym', imgPath: 'tkan (95).jpg' },
    { nazwa: 'zwierzaki w kółkach na niebieskim', imgPath: 'tkan (96).jpg' },
    { nazwa: 'zygzak szary', imgPath: 'tkan (97).jpg' }
  ];

  pobierzTkaniny() {
    return this.listaTkanin.slice();
  }
}